### ISSUE TITLE
Forward Compatible Context

### ISSUE THREAD

**Issue by fenbf** [daw42/glslcookbook#29]
should Forward Compatible Context flag be really used?

I've found this [answer at StackExchange](http://gamedev.stackexchange.com/a/28332/34216) and it says: 

    Never, ever, ever, EVER use FORWARD_COMPATIBLE for ANYTHING.

So maybe this line from main.cpp

```C++
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
```

should be simply removed?

**Comment by wreardan** [comment]
I think you are mistaking GLUT and GLFW (two different libraries).  I believe that forward compatible contexts can be used safely in GLFW.

Wes

**Comment by fenbf** [comment]
all in all those flags goes to native OS API calls (wgl, glx...) and even on OpenGL wiki page [Creating OpenGL Context WGL](https://www.opengl.org/wiki/Creating_an_OpenGL_Context_(WGL)) there is a note that forward compatible context should not be used.

**Comment by wreardan** [comment]
This book is based on OpenGL 4.0 so I believe that a forward compatible context may be appropriate. Also the OpenGL wiki is not necessarily the most up to date: that link you referenced is OpenGL 3.x

Wes

**Comment by daw42** [comment]
Thanks for the note.  It's interesting that people have such strong opinions about this.

I chose to use a forward compatible context because I wanted to make sure that I was only using non-deprecated features in a 4.x core profile.  I think that the comment on StackExchange is a bit over the top.  If you really want to stick with just non-deprecated features, there's nothing wrong with using a forward compatible context.  The statement on the OpenGL Wiki doesn't elaborate as to why one should not use a forward compatible context.  I'd be interested to hear why that statement is there.

Regardless, it wouldn't hurt to remove it, but I currently don't see the harm of using it.
