### ISSUE TITLE
tgaio.cpp won't compile on Mac El Capitan with xcode

### ISSUE THREAD

**Issue by sp-erik-podetti** [daw42/glslcookbook#41]
![screenshot 2016-04-30 17 41 16](https://cloud.githubusercontent.com/assets/18529748/14937010/d67cc500-0efa-11e6-94ff-f593a392c427.png)

**Comment by daw42** [comment]
Interesting, perhaps `ifstream` and `ofstream` are globally defined somewhere in the MacOS libs.   Please try replacing `ifstream` with `std::ifstream` and `ofstream` with `std::ofstream`.   Thanks!

**Comment by sp-erik-podetti** [comment]
Expliciting putting the namespace fixed that error but now I'm getting this:
<img width="1019" alt="screenshot 2016-05-01 13 22 35" src="https://cloud.githubusercontent.com/assets/18529748/14941561/32fa67b0-0fa0-11e6-9561-996dc1419fde.png">

I have installed the last X11 Quartz version if it's importanta

**Comment by daw42** [comment]
I just pushed up a change that should fix this issue (7c9f5fd).  You're welcome to give it a try.

Unfortunately, even if it does compile on OSX, it may not execute.  As you probably know, MacOS only provides support for OpenGL 4.1 core.  It does not, and probably will never support higher versions of OpenGL, now that Apple is pushing their Metal API.  Some of the examples in this code require newer versions.  The primary examples being the compute shaders (Chapter 10) that require OpenGL 4.3, and some of the other examples require 4.2.  For example, the texture examples make use of immutable textures which were introduced in 4.2.

Having said that, most examples should run (possibly with a few changes) on OpenGL 4.1.  It would be interesting to update the code so that it could support users who want to use MacOS.   The best way to do that would be to just downgrade the examples that can support 4.1.  To make it work, you'll need to change the version selection code in `main.cpp` and change the version specifiers in the shaders.  There will likely need to be other changes as well.  However, you should be able to start with chapter 1 which should be fairly easy to get working.  Once that's working you could move on to other examples.  If I have time, I'll be happy to help out.

**Comment by HoMeBoYErik** [comment]
Many many thank you! I didn't thought that Metal will be an obstacle for OpenGL to be supported, but yes you're probably right and Mac users will be stuck with 4.1
As game developer I develop on Mac 95% of the time and it would be great to run new shaders on it. 
Thank you for your effort. I'll give a try to the modifications.

**Comment by daw42** [comment]
Ok, I'm working on updating the code to support MacOS (OpenGL 4.1).  I have already pushed fixes for Chapter 1, so the Chapter 1 examples (except basic-debug) should now work on OSX.  

You can track progress in #42 .  I'm closing this issue, please refer to #42 instead.  Thanks!
